### ISSUE TITLE
Update station hub B: 260

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3253]
## Description

The longer we leave the issues with station hub the harder it will be to get everyone on to the new version (as updater is broken in current version). We need to do an update now.

### Criteria
- Add a forgotten password screen with a button on the login view
- Fix the auto updater by getting the PID of the hub when it is running and force close the process from the update process when it starts the patching
- Update the auto updater to handle multiple arbitrary files
- Turn off the Remove Old Versions automatically checkbox by default
- Refresh the server list every 10 seconds or so
- Refresh the PR list whenever someone presses the refresh button
- Make the OSX app a folder instead as it needs to be pulled into the applications folder with out being a single app (as per the single file build bug)

**Comment by DooblyNoobly** [comment]
A start up exception that needs a fix:

```
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: External component has thrown an exception.
   at System.Globalization.CompareInfo.CompareString(ReadOnlySpan`1 string1, ReadOnlySpan`1 string2, CompareOptions options)
   at System.Globalization.CompareInfo.Compare(String string1, String string2, CompareOptions options)
   at System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant()
   at System.Globalization.TextInfo.ChangeCaseCommon[TConversion](String source)
   at System.Globalization.TextInfo.ToLower(String str)
   at System.String.ToLowerInvariant()
   at System.UriParser.IsKnownScheme(String schemeName)
   at Avalonia.Shared.PlatformSupport.AssetLoader.RegisterResUriParsers()
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatformServices.Register(Assembly assembly)
   at Avalonia.AppBuilder.<>c.<.ctor>b__0_0(AppBuilder builder)
   at Avalonia.Controls.AppBuilderBase`1.<>c__DisplayClass44_0.<.ctor>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at UnitystationLauncher.Program.Main(String[] args) in D:\GitHub\UnitystationLauncher\UnitystationLauncher\Program.cs:line 9
```

issue logged: https://github.com/AvaloniaUI/Avalonia/issues/3601

**Comment by DooblyNoobly** [comment]
updated to 260 as its been 4 full days of work so far

**Comment by DooblyNoobly** [comment]
Completed as per this reddit post: https://www.reddit.com/r/unitystation/comments/f93em9/station_hub_926_has_been_released_please/
