### ISSUE TITLE
Having " in your password causes registration to fail.

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#5923]
### Environment
- Game Version: 926
- OS Version: Linux

### Detailed description of bug

When trying to to create an account on station hub the request will fail because of an invalid json if you have a " in you password. Have had this problem with the linux build from the website and the version on flathub.

Console output is as follows:

```[15:24:55 INF] Build Number: 926
[15:25:09 ERR] Login failed
Firebase.Auth.FirebaseAuthException: Exception occured while authenticating.
Url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key={0}
Request Data: {"email":"test@test.com","password":"test"test","returnSecureToken":true}
Response: {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Expected , or } after key:value pair.\n:\"test\"test\",\"returnSecureT\n       ^",
    "errors": [
      {
        "message": "Invalid JSON payload received. Expected , or } after key:value pair.\n:\"test\"test\",\"returnSecureT\n       ^",
        "domain": "global",
        "reason": "parseError"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}

Reason: Undefined
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Firebase.Auth.FirebaseAuthProvider.ExecuteWithPostContentAsync(String googleUrl, String postContent)
   --- End of inner exception stack trace ---
   at Firebase.Auth.FirebaseAuthProvider.ExecuteWithPostContentAsync(String googleUrl, String postContent)
   at Firebase.Auth.FirebaseAuthProvider.CreateUserWithEmailAndPasswordAsync(String email, String password, String displayName, Boolean sendVerificationEmail)
   at UnitystationLauncher.Models.AuthManager.CreateAccount(String username, String email, String password) in /run/build/StationHub/UnitystationLauncher/Models/AuthManager.cs:line 119
   at UnitystationLauncher.ViewModels.SignUpViewModel.UserCreate() in /run/build/StationHub/UnitystationLauncher/ViewModels/SignUpViewModel.cs:line 108
```

### Steps to reproduce

Just try to register.

**Comment by MaxIsJoe** [comment]
I assume this was fixed when we moved to django. So putting a "needs reproduction" tag on this until we get a confirmation.

**Comment by craftxbox** [comment]
Confirmed this no longer manifests

**Comment by MaxIsJoe** [comment]
alright, fixed.
